### ISSUE TITLE
disable x3dom gamma correction ?

### ISSUE THREAD

**Issue by andreasplesch** [jamesleesaunders/d3-x3d#122]
x3dom has gamma correction enabled by default. It can be disabled which results in more saturated colors which are then similar to x_ite lighting: https://doc.x3dom.org/tutorials/lighting/gamma/index.html

Here are the examples with gamma correction disabled:

https://andreasplesch.github.io/d3-x3d/examples/X3DOM/chart/AreaChartMultiSeries.html
https://andreasplesch.github.io/d3-x3d/examples/X3DOM/chart/AreaChartMultiSeries2.html
https://andreasplesch.github.io/d3-x3d/examples/X3DOM/chart/BarChartVertical.html
https://andreasplesch.github.io/d3-x3d/examples/X3DOM/chart/BarChartMultiSeries.html
https://andreasplesch.github.io/d3-x3d/examples/X3DOM/chart/BubbleChart.html
https://andreasplesch.github.io/d3-x3d/examples/X3DOM/chart/ScatterPlot.html
https://andreasplesch.github.io/d3-x3d/examples/X3DOM/chart/SurfacePlot.html
https://andreasplesch.github.io/d3-x3d/examples/X3DOM/chart/RibbonChartMultiSeries.html
https://andreasplesch.github.io/d3-x3d/examples/X3DOM/chart/VectorFieldChart.html

Here are the examples with x3dom gamma correction enabled:

https://jamesleesaunders.github.io/d3-x3d/#examples

**Comment by jamesleesaunders** [comment]
Thanks @andreasplesch ! This was something I have been meaning to look into, I noticed the colour saturation difference when x3dom moved to 1.8. 

Did you want to put in a PR with your fixes?

**Comment by andreasplesch** [comment]
x3dom uses a non-standard Environment node for these settings which means that x_ite generates a warning in the console about not recognizing such a node. Would you still want to go ahead ?

Also, I noticed there is a lot of code duplication for setting up the scene for each chart (making a x3d, scene and background element for each chart). I can insert an Environment node for each chart separately but it may start make sense to centralize and share utility functions between charts. I would not know how to do that best given the code structure.

**Comment by jamesleesaunders** [comment]
I have just pulled the changes over from your gammaCorrection branch and merged them in.
Rather than modify the 'dist' files directly (which are built by npm) I have translated your changes into the src/charts files (https://github.com/jamesleesaunders/d3-x3d/commit/699d68a72995744ad99ef3eb0ad4e6e45f6aecf9) and rebuilt the dist files again.

As you point out there is a lot of code duplication where each of the src/chart/* files each has an identical createBase() function which created the x3d base, background (and now environment) tags. This createBase() does indeed need moving to a DRYer base module type place.

> x3dom uses a non-standard Environment node for these settings which means that x_ite generates a warning in the console about not recognizing such a node. Would you still want to go ahead ?

ah, I have already merged in your changes, I'll have a look at how this manifests itself for x_ite and make may have to implement something which detects whether it is running on x3dom or x_ite. 
I do want to try and support x3dom and x_ite equally and ideally I don't want to drift too far off standard, do you know the reason why this was switched between x3dom 1.7.2 and 1.8 ?

**Comment by jamesleesaunders** [comment]
huurm, yes, 
`x_ite.min.js:19 XML Parser Error: Unkown node type 'ENVIRONMENT', you probably have insufficient component/profile statements.`
Not the end of the world, but I'll have a think whether to revert this for the moment.

**Comment by andreasplesch** [comment]
No, I do not know why gamma correction is linear by default. Presumably, it is considered more correct and more standard.

**Comment by andreasplesch** [comment]
Another way to switch to no gamma correction by default would be to patch up x3dom after loading.

Here is one way to do that:

https://github.com/andreasplesch/d3-x3d/commit/955eb9ea484bde38539ea72d6f2a20e789c9406b

https://raw.githack.com/andreasplesch/d3-x3d/x3domGamma/examples/X3DOM/chart/ScatterPlot.html

x_ite does not show warnings this way:
https://raw.githack.com/andreasplesch/d3-x3d/x3domGamma/examples/X_ITE/chart/ScatterPlot.html

But it could be considered hackish.

**Comment by jamesleesaunders** [comment]
Fixed by https://github.com/jamesleesaunders/d3-x3d/commit/142ebe30f5016e8ca8c879a2668dbcc12318b883
